numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batchb/v6_batchb_5_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batchb/v6_batchb_5_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batchb/v6_batchb_5_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batchb/v6_batchb_5_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batchb/v6_batchb_netParams.py
Importing netParams from ../data/v6_batchb/v6_batchb_netParams.py
Importing netParams from ../data/v6_batchb/v6_batchb_netParams.py

Start time:  2021-08-19 21:34:32.774301
Importing netParams from ../data/v6_batchb/v6_batchb_netParams.py

Creating network of 55 cell populations on 4 hosts...
  Number of cells on node 1: 7837 
  Number of cells on node 2: 7836 
  Number of cells on node 3: 7836 
  Number of cells on node 0: 7837 
  Done; cell creation time = 35.15 s.
Making connections...
  Number of connections on node 3: 228281 
  Number of synaptic contacts on node 3: 1728890 
  Number of connections on node 0: 229594 
  Number of synaptic contacts on node 0: 1738630 
  Number of connections on node 1: 229121 
  Number of synaptic contacts on node 1: 1734570 
  Done; cell connection time = 1690.50 s.
  Number of connections on node 2: 227682 
  Number of synaptic contacts on node 2: 1724752 

Gathering data...
  Done; gather time = 114.68 s.

Analyzing...
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f24b68de2c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f3560044308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f039037a2c8>)
  Cells: 31346
  Connections: 914678 (29.18 per cell)
  Synaptic contacts: 6926842 (220.98 per cell)
Plotting connectivity matrix...
Saving figure data as ../data/v6_batchb/v6_batchb_5_pop_numConns_matrix.json ... 
